language: python

python:
  - "3.8.0"

env:
  - PYTHONPATH=.

before_install:
  - curl -s -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.3.0-amd64.deb
  - sudo dpkg -i --force-confnew elasticsearch-7.3.0-amd64.deb
  - sudo sed -i.old 's/-Xms1g/-Xms128m/' /etc/elasticsearch/jvm.options
  - sudo sed -i.old 's/-Xmx1g/-Xmx128m/' /etc/elasticsearch/jvm.options
  - echo -e '-XX:+DisableExplicitGC\n-Djdk.io.permissionsUseCanonicalPath=true\n-Dlog4j.skipJansi=true\n-server\n' | sudo tee -a /etc/elasticsearch/jvm.options
  - sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
  - sudo systemctl start elasticsearch
  - until curl --silent -XGET --fail http://127.0.0.1:9200; do printf '.'; sleep 1; done

install:
  - pip install -r requirements.txt

script:
  - pytest tests/unit
  - pytest tests/functional
