language: python

services:
  - docker

before_install:
  - docker build -t poc-ci .
  - docker ps -a

script:
  - docker run poc-ci bash -c "pytest tests/unit"
  - docker run poc-ci bash -c "pytest tests/functional"
