language: python

python:
  - "3.8.0"

env:
  - PYTHONPATH=.

services:
  - docker
  - elasticsearch

before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.3.0-amd64.deb && sudo dpkg -i --force-confnew elasticsearch-7.3.0-amd64.deb && sudo service elasticsearch restart

install:
  - pip install -r requirements.txt

before_script:
  - sleep 30

script:
  - pytest tests/unit
  - pytest tests/functional
