language: python

python:
  - "3.8.0"

env:
  - PYTHONPATH=.

before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.3.0-amd64.deb
  - sudo dpkg -i --force-confnew elasticsearch-7.3.0-amd64.deb
  - sudo -i service elasticsearch start
  - until curl --silent -XGET --fail http://127.0.0.1:9200; do printf '.'; sleep 1; done

install:
  - pip install -r requirements.txt

script:
  - pytest tests/unit
  - pytest tests/functional
