version: '3'

services:
    elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
        ports:
            - 9200:9200
        environment:
            - TZ=UTC
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms128m -Xmx128m"

    app:
        build: .
        command: tail -f /dev/null
        environment:
            ELASTIC_HOST: elastic
        depends_on:
            - elastic
        volumes:
            - .:/usr/share/src
